[package]
name = "capataz-monitor-server"
version = "0.1.0"
authors = ["roman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.7.0"