// This file is generated by rust-protobuf 2.8.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `events.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_0;

#[derive(PartialEq,Clone,Default)]
pub struct ProcessInfo {
    // message fields
    pub event_id: ::std::string::String,
    pub process_id: ::std::string::String,
    pub parent_id: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ProcessInfo {
    fn default() -> &'a ProcessInfo {
        <ProcessInfo as ::protobuf::Message>::default_instance()
    }
}

impl ProcessInfo {
    pub fn new() -> ProcessInfo {
        ::std::default::Default::default()
    }

    // string event_id = 1;


    pub fn get_event_id(&self) -> &str {
        &self.event_id
    }
    pub fn clear_event_id(&mut self) {
        self.event_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_event_id(&mut self, v: ::std::string::String) {
        self.event_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_event_id(&mut self) -> &mut ::std::string::String {
        &mut self.event_id
    }

    // Take field
    pub fn take_event_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.event_id, ::std::string::String::new())
    }

    // string process_id = 2;


    pub fn get_process_id(&self) -> &str {
        &self.process_id
    }
    pub fn clear_process_id(&mut self) {
        self.process_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_process_id(&mut self, v: ::std::string::String) {
        self.process_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_process_id(&mut self) -> &mut ::std::string::String {
        &mut self.process_id
    }

    // Take field
    pub fn take_process_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.process_id, ::std::string::String::new())
    }

    // string parent_id = 3;


    pub fn get_parent_id(&self) -> &str {
        &self.parent_id
    }
    pub fn clear_parent_id(&mut self) {
        self.parent_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_parent_id(&mut self, v: ::std::string::String) {
        self.parent_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_parent_id(&mut self) -> &mut ::std::string::String {
        &mut self.parent_id
    }

    // Take field
    pub fn take_parent_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.parent_id, ::std::string::String::new())
    }
}

impl ::protobuf::Message for ProcessInfo {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.event_id)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.process_id)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.parent_id)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.event_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.event_id);
        }
        if !self.process_id.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.process_id);
        }
        if !self.parent_id.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.parent_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.event_id.is_empty() {
            os.write_string(1, &self.event_id)?;
        }
        if !self.process_id.is_empty() {
            os.write_string(2, &self.process_id)?;
        }
        if !self.parent_id.is_empty() {
            os.write_string(3, &self.parent_id)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ProcessInfo {
        ProcessInfo::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "event_id",
                    |m: &ProcessInfo| { &m.event_id },
                    |m: &mut ProcessInfo| { &mut m.event_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "process_id",
                    |m: &ProcessInfo| { &m.process_id },
                    |m: &mut ProcessInfo| { &mut m.process_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "parent_id",
                    |m: &ProcessInfo| { &m.parent_id },
                    |m: &mut ProcessInfo| { &mut m.parent_id },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ProcessInfo>(
                    "ProcessInfo",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ProcessInfo {
        static mut instance: ::protobuf::lazy::Lazy<ProcessInfo> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ProcessInfo,
        };
        unsafe {
            instance.get(ProcessInfo::new)
        }
    }
}

impl ::protobuf::Clear for ProcessInfo {
    fn clear(&mut self) {
        self.event_id.clear();
        self.process_id.clear();
        self.parent_id.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ProcessInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProcessInfo {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ProcessStarted {
    // message fields
    pub info: ::protobuf::SingularPtrField<ProcessInfo>,
    pub tag: ProcessTag,
    pub create_timestamp: ::protobuf::SingularPtrField<::protobuf::well_known_types::Timestamp>,
    pub first_restart_timestamp: ::protobuf::SingularPtrField<::protobuf::well_known_types::Timestamp>,
    pub restart_count: u32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ProcessStarted {
    fn default() -> &'a ProcessStarted {
        <ProcessStarted as ::protobuf::Message>::default_instance()
    }
}

impl ProcessStarted {
    pub fn new() -> ProcessStarted {
        ::std::default::Default::default()
    }

    // .capataz.events.ProcessInfo info = 1;


    pub fn get_info(&self) -> &ProcessInfo {
        self.info.as_ref().unwrap_or_else(|| ProcessInfo::default_instance())
    }
    pub fn clear_info(&mut self) {
        self.info.clear();
    }

    pub fn has_info(&self) -> bool {
        self.info.is_some()
    }

    // Param is passed by value, moved
    pub fn set_info(&mut self, v: ProcessInfo) {
        self.info = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_info(&mut self) -> &mut ProcessInfo {
        if self.info.is_none() {
            self.info.set_default();
        }
        self.info.as_mut().unwrap()
    }

    // Take field
    pub fn take_info(&mut self) -> ProcessInfo {
        self.info.take().unwrap_or_else(|| ProcessInfo::new())
    }

    // .capataz.events.ProcessTag tag = 2;


    pub fn get_tag(&self) -> ProcessTag {
        self.tag
    }
    pub fn clear_tag(&mut self) {
        self.tag = ProcessTag::WORKER;
    }

    // Param is passed by value, moved
    pub fn set_tag(&mut self, v: ProcessTag) {
        self.tag = v;
    }

    // .google.protobuf.Timestamp create_timestamp = 3;


    pub fn get_create_timestamp(&self) -> &::protobuf::well_known_types::Timestamp {
        self.create_timestamp.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::Timestamp::default_instance())
    }
    pub fn clear_create_timestamp(&mut self) {
        self.create_timestamp.clear();
    }

    pub fn has_create_timestamp(&self) -> bool {
        self.create_timestamp.is_some()
    }

    // Param is passed by value, moved
    pub fn set_create_timestamp(&mut self, v: ::protobuf::well_known_types::Timestamp) {
        self.create_timestamp = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_create_timestamp(&mut self) -> &mut ::protobuf::well_known_types::Timestamp {
        if self.create_timestamp.is_none() {
            self.create_timestamp.set_default();
        }
        self.create_timestamp.as_mut().unwrap()
    }

    // Take field
    pub fn take_create_timestamp(&mut self) -> ::protobuf::well_known_types::Timestamp {
        self.create_timestamp.take().unwrap_or_else(|| ::protobuf::well_known_types::Timestamp::new())
    }

    // .google.protobuf.Timestamp first_restart_timestamp = 4;


    pub fn get_first_restart_timestamp(&self) -> &::protobuf::well_known_types::Timestamp {
        self.first_restart_timestamp.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::Timestamp::default_instance())
    }
    pub fn clear_first_restart_timestamp(&mut self) {
        self.first_restart_timestamp.clear();
    }

    pub fn has_first_restart_timestamp(&self) -> bool {
        self.first_restart_timestamp.is_some()
    }

    // Param is passed by value, moved
    pub fn set_first_restart_timestamp(&mut self, v: ::protobuf::well_known_types::Timestamp) {
        self.first_restart_timestamp = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_first_restart_timestamp(&mut self) -> &mut ::protobuf::well_known_types::Timestamp {
        if self.first_restart_timestamp.is_none() {
            self.first_restart_timestamp.set_default();
        }
        self.first_restart_timestamp.as_mut().unwrap()
    }

    // Take field
    pub fn take_first_restart_timestamp(&mut self) -> ::protobuf::well_known_types::Timestamp {
        self.first_restart_timestamp.take().unwrap_or_else(|| ::protobuf::well_known_types::Timestamp::new())
    }

    // uint32 restart_count = 5;


    pub fn get_restart_count(&self) -> u32 {
        self.restart_count
    }
    pub fn clear_restart_count(&mut self) {
        self.restart_count = 0;
    }

    // Param is passed by value, moved
    pub fn set_restart_count(&mut self, v: u32) {
        self.restart_count = v;
    }
}

impl ::protobuf::Message for ProcessStarted {
    fn is_initialized(&self) -> bool {
        for v in &self.info {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.create_timestamp {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.first_restart_timestamp {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.info)?;
                },
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.tag, 2, &mut self.unknown_fields)?
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.create_timestamp)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.first_restart_timestamp)?;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.restart_count = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.tag != ProcessTag::WORKER {
            my_size += ::protobuf::rt::enum_size(2, self.tag);
        }
        if let Some(ref v) = self.create_timestamp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.first_restart_timestamp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.restart_count != 0 {
            my_size += ::protobuf::rt::value_size(5, self.restart_count, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.info.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.tag != ProcessTag::WORKER {
            os.write_enum(2, self.tag.value())?;
        }
        if let Some(ref v) = self.create_timestamp.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.first_restart_timestamp.as_ref() {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.restart_count != 0 {
            os.write_uint32(5, self.restart_count)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ProcessStarted {
        ProcessStarted::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ProcessInfo>>(
                    "info",
                    |m: &ProcessStarted| { &m.info },
                    |m: &mut ProcessStarted| { &mut m.info },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<ProcessTag>>(
                    "tag",
                    |m: &ProcessStarted| { &m.tag },
                    |m: &mut ProcessStarted| { &mut m.tag },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Timestamp>>(
                    "create_timestamp",
                    |m: &ProcessStarted| { &m.create_timestamp },
                    |m: &mut ProcessStarted| { &mut m.create_timestamp },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Timestamp>>(
                    "first_restart_timestamp",
                    |m: &ProcessStarted| { &m.first_restart_timestamp },
                    |m: &mut ProcessStarted| { &mut m.first_restart_timestamp },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "restart_count",
                    |m: &ProcessStarted| { &m.restart_count },
                    |m: &mut ProcessStarted| { &mut m.restart_count },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ProcessStarted>(
                    "ProcessStarted",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ProcessStarted {
        static mut instance: ::protobuf::lazy::Lazy<ProcessStarted> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ProcessStarted,
        };
        unsafe {
            instance.get(ProcessStarted::new)
        }
    }
}

impl ::protobuf::Clear for ProcessStarted {
    fn clear(&mut self) {
        self.info.clear();
        self.tag = ProcessTag::WORKER;
        self.create_timestamp.clear();
        self.first_restart_timestamp.clear();
        self.restart_count = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ProcessStarted {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProcessStarted {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ProcessTerminated {
    // message fields
    pub info: ::protobuf::SingularPtrField<ProcessInfo>,
    pub tag: ProcessTag,
    pub create_timestamp: ::protobuf::SingularPtrField<::protobuf::well_known_types::Timestamp>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ProcessTerminated {
    fn default() -> &'a ProcessTerminated {
        <ProcessTerminated as ::protobuf::Message>::default_instance()
    }
}

impl ProcessTerminated {
    pub fn new() -> ProcessTerminated {
        ::std::default::Default::default()
    }

    // .capataz.events.ProcessInfo info = 1;


    pub fn get_info(&self) -> &ProcessInfo {
        self.info.as_ref().unwrap_or_else(|| ProcessInfo::default_instance())
    }
    pub fn clear_info(&mut self) {
        self.info.clear();
    }

    pub fn has_info(&self) -> bool {
        self.info.is_some()
    }

    // Param is passed by value, moved
    pub fn set_info(&mut self, v: ProcessInfo) {
        self.info = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_info(&mut self) -> &mut ProcessInfo {
        if self.info.is_none() {
            self.info.set_default();
        }
        self.info.as_mut().unwrap()
    }

    // Take field
    pub fn take_info(&mut self) -> ProcessInfo {
        self.info.take().unwrap_or_else(|| ProcessInfo::new())
    }

    // .capataz.events.ProcessTag tag = 2;


    pub fn get_tag(&self) -> ProcessTag {
        self.tag
    }
    pub fn clear_tag(&mut self) {
        self.tag = ProcessTag::WORKER;
    }

    // Param is passed by value, moved
    pub fn set_tag(&mut self, v: ProcessTag) {
        self.tag = v;
    }

    // .google.protobuf.Timestamp create_timestamp = 3;


    pub fn get_create_timestamp(&self) -> &::protobuf::well_known_types::Timestamp {
        self.create_timestamp.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::Timestamp::default_instance())
    }
    pub fn clear_create_timestamp(&mut self) {
        self.create_timestamp.clear();
    }

    pub fn has_create_timestamp(&self) -> bool {
        self.create_timestamp.is_some()
    }

    // Param is passed by value, moved
    pub fn set_create_timestamp(&mut self, v: ::protobuf::well_known_types::Timestamp) {
        self.create_timestamp = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_create_timestamp(&mut self) -> &mut ::protobuf::well_known_types::Timestamp {
        if self.create_timestamp.is_none() {
            self.create_timestamp.set_default();
        }
        self.create_timestamp.as_mut().unwrap()
    }

    // Take field
    pub fn take_create_timestamp(&mut self) -> ::protobuf::well_known_types::Timestamp {
        self.create_timestamp.take().unwrap_or_else(|| ::protobuf::well_known_types::Timestamp::new())
    }
}

impl ::protobuf::Message for ProcessTerminated {
    fn is_initialized(&self) -> bool {
        for v in &self.info {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.create_timestamp {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.info)?;
                },
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.tag, 2, &mut self.unknown_fields)?
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.create_timestamp)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.tag != ProcessTag::WORKER {
            my_size += ::protobuf::rt::enum_size(2, self.tag);
        }
        if let Some(ref v) = self.create_timestamp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.info.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.tag != ProcessTag::WORKER {
            os.write_enum(2, self.tag.value())?;
        }
        if let Some(ref v) = self.create_timestamp.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ProcessTerminated {
        ProcessTerminated::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ProcessInfo>>(
                    "info",
                    |m: &ProcessTerminated| { &m.info },
                    |m: &mut ProcessTerminated| { &mut m.info },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<ProcessTag>>(
                    "tag",
                    |m: &ProcessTerminated| { &m.tag },
                    |m: &mut ProcessTerminated| { &mut m.tag },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Timestamp>>(
                    "create_timestamp",
                    |m: &ProcessTerminated| { &m.create_timestamp },
                    |m: &mut ProcessTerminated| { &mut m.create_timestamp },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ProcessTerminated>(
                    "ProcessTerminated",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ProcessTerminated {
        static mut instance: ::protobuf::lazy::Lazy<ProcessTerminated> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ProcessTerminated,
        };
        unsafe {
            instance.get(ProcessTerminated::new)
        }
    }
}

impl ::protobuf::Clear for ProcessTerminated {
    fn clear(&mut self) {
        self.info.clear();
        self.tag = ProcessTag::WORKER;
        self.create_timestamp.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ProcessTerminated {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProcessTerminated {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ProcessCompleted {
    // message fields
    pub info: ::protobuf::SingularPtrField<ProcessInfo>,
    pub tag: ProcessTag,
    pub create_timestamp: ::protobuf::SingularPtrField<::protobuf::well_known_types::Timestamp>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ProcessCompleted {
    fn default() -> &'a ProcessCompleted {
        <ProcessCompleted as ::protobuf::Message>::default_instance()
    }
}

impl ProcessCompleted {
    pub fn new() -> ProcessCompleted {
        ::std::default::Default::default()
    }

    // .capataz.events.ProcessInfo info = 1;


    pub fn get_info(&self) -> &ProcessInfo {
        self.info.as_ref().unwrap_or_else(|| ProcessInfo::default_instance())
    }
    pub fn clear_info(&mut self) {
        self.info.clear();
    }

    pub fn has_info(&self) -> bool {
        self.info.is_some()
    }

    // Param is passed by value, moved
    pub fn set_info(&mut self, v: ProcessInfo) {
        self.info = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_info(&mut self) -> &mut ProcessInfo {
        if self.info.is_none() {
            self.info.set_default();
        }
        self.info.as_mut().unwrap()
    }

    // Take field
    pub fn take_info(&mut self) -> ProcessInfo {
        self.info.take().unwrap_or_else(|| ProcessInfo::new())
    }

    // .capataz.events.ProcessTag tag = 2;


    pub fn get_tag(&self) -> ProcessTag {
        self.tag
    }
    pub fn clear_tag(&mut self) {
        self.tag = ProcessTag::WORKER;
    }

    // Param is passed by value, moved
    pub fn set_tag(&mut self, v: ProcessTag) {
        self.tag = v;
    }

    // .google.protobuf.Timestamp create_timestamp = 3;


    pub fn get_create_timestamp(&self) -> &::protobuf::well_known_types::Timestamp {
        self.create_timestamp.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::Timestamp::default_instance())
    }
    pub fn clear_create_timestamp(&mut self) {
        self.create_timestamp.clear();
    }

    pub fn has_create_timestamp(&self) -> bool {
        self.create_timestamp.is_some()
    }

    // Param is passed by value, moved
    pub fn set_create_timestamp(&mut self, v: ::protobuf::well_known_types::Timestamp) {
        self.create_timestamp = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_create_timestamp(&mut self) -> &mut ::protobuf::well_known_types::Timestamp {
        if self.create_timestamp.is_none() {
            self.create_timestamp.set_default();
        }
        self.create_timestamp.as_mut().unwrap()
    }

    // Take field
    pub fn take_create_timestamp(&mut self) -> ::protobuf::well_known_types::Timestamp {
        self.create_timestamp.take().unwrap_or_else(|| ::protobuf::well_known_types::Timestamp::new())
    }
}

impl ::protobuf::Message for ProcessCompleted {
    fn is_initialized(&self) -> bool {
        for v in &self.info {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.create_timestamp {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.info)?;
                },
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.tag, 2, &mut self.unknown_fields)?
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.create_timestamp)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.tag != ProcessTag::WORKER {
            my_size += ::protobuf::rt::enum_size(2, self.tag);
        }
        if let Some(ref v) = self.create_timestamp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.info.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.tag != ProcessTag::WORKER {
            os.write_enum(2, self.tag.value())?;
        }
        if let Some(ref v) = self.create_timestamp.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ProcessCompleted {
        ProcessCompleted::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ProcessInfo>>(
                    "info",
                    |m: &ProcessCompleted| { &m.info },
                    |m: &mut ProcessCompleted| { &mut m.info },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<ProcessTag>>(
                    "tag",
                    |m: &ProcessCompleted| { &m.tag },
                    |m: &mut ProcessCompleted| { &mut m.tag },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Timestamp>>(
                    "create_timestamp",
                    |m: &ProcessCompleted| { &m.create_timestamp },
                    |m: &mut ProcessCompleted| { &mut m.create_timestamp },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ProcessCompleted>(
                    "ProcessCompleted",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ProcessCompleted {
        static mut instance: ::protobuf::lazy::Lazy<ProcessCompleted> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ProcessCompleted,
        };
        unsafe {
            instance.get(ProcessCompleted::new)
        }
    }
}

impl ::protobuf::Clear for ProcessCompleted {
    fn clear(&mut self) {
        self.info.clear();
        self.tag = ProcessTag::WORKER;
        self.create_timestamp.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ProcessCompleted {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProcessCompleted {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ProcessFailed {
    // message fields
    pub info: ::protobuf::SingularPtrField<ProcessInfo>,
    pub tag: ProcessTag,
    pub error: ::std::string::String,
    pub create_timestamp: ::protobuf::SingularPtrField<::protobuf::well_known_types::Timestamp>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ProcessFailed {
    fn default() -> &'a ProcessFailed {
        <ProcessFailed as ::protobuf::Message>::default_instance()
    }
}

impl ProcessFailed {
    pub fn new() -> ProcessFailed {
        ::std::default::Default::default()
    }

    // .capataz.events.ProcessInfo info = 1;


    pub fn get_info(&self) -> &ProcessInfo {
        self.info.as_ref().unwrap_or_else(|| ProcessInfo::default_instance())
    }
    pub fn clear_info(&mut self) {
        self.info.clear();
    }

    pub fn has_info(&self) -> bool {
        self.info.is_some()
    }

    // Param is passed by value, moved
    pub fn set_info(&mut self, v: ProcessInfo) {
        self.info = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_info(&mut self) -> &mut ProcessInfo {
        if self.info.is_none() {
            self.info.set_default();
        }
        self.info.as_mut().unwrap()
    }

    // Take field
    pub fn take_info(&mut self) -> ProcessInfo {
        self.info.take().unwrap_or_else(|| ProcessInfo::new())
    }

    // .capataz.events.ProcessTag tag = 2;


    pub fn get_tag(&self) -> ProcessTag {
        self.tag
    }
    pub fn clear_tag(&mut self) {
        self.tag = ProcessTag::WORKER;
    }

    // Param is passed by value, moved
    pub fn set_tag(&mut self, v: ProcessTag) {
        self.tag = v;
    }

    // string error = 3;


    pub fn get_error(&self) -> &str {
        &self.error
    }
    pub fn clear_error(&mut self) {
        self.error.clear();
    }

    // Param is passed by value, moved
    pub fn set_error(&mut self, v: ::std::string::String) {
        self.error = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_error(&mut self) -> &mut ::std::string::String {
        &mut self.error
    }

    // Take field
    pub fn take_error(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.error, ::std::string::String::new())
    }

    // .google.protobuf.Timestamp create_timestamp = 4;


    pub fn get_create_timestamp(&self) -> &::protobuf::well_known_types::Timestamp {
        self.create_timestamp.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::Timestamp::default_instance())
    }
    pub fn clear_create_timestamp(&mut self) {
        self.create_timestamp.clear();
    }

    pub fn has_create_timestamp(&self) -> bool {
        self.create_timestamp.is_some()
    }

    // Param is passed by value, moved
    pub fn set_create_timestamp(&mut self, v: ::protobuf::well_known_types::Timestamp) {
        self.create_timestamp = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_create_timestamp(&mut self) -> &mut ::protobuf::well_known_types::Timestamp {
        if self.create_timestamp.is_none() {
            self.create_timestamp.set_default();
        }
        self.create_timestamp.as_mut().unwrap()
    }

    // Take field
    pub fn take_create_timestamp(&mut self) -> ::protobuf::well_known_types::Timestamp {
        self.create_timestamp.take().unwrap_or_else(|| ::protobuf::well_known_types::Timestamp::new())
    }
}

impl ::protobuf::Message for ProcessFailed {
    fn is_initialized(&self) -> bool {
        for v in &self.info {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.create_timestamp {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.info)?;
                },
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.tag, 2, &mut self.unknown_fields)?
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.error)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.create_timestamp)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.tag != ProcessTag::WORKER {
            my_size += ::protobuf::rt::enum_size(2, self.tag);
        }
        if !self.error.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.error);
        }
        if let Some(ref v) = self.create_timestamp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.info.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.tag != ProcessTag::WORKER {
            os.write_enum(2, self.tag.value())?;
        }
        if !self.error.is_empty() {
            os.write_string(3, &self.error)?;
        }
        if let Some(ref v) = self.create_timestamp.as_ref() {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ProcessFailed {
        ProcessFailed::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ProcessInfo>>(
                    "info",
                    |m: &ProcessFailed| { &m.info },
                    |m: &mut ProcessFailed| { &mut m.info },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<ProcessTag>>(
                    "tag",
                    |m: &ProcessFailed| { &m.tag },
                    |m: &mut ProcessFailed| { &mut m.tag },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "error",
                    |m: &ProcessFailed| { &m.error },
                    |m: &mut ProcessFailed| { &mut m.error },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Timestamp>>(
                    "create_timestamp",
                    |m: &ProcessFailed| { &m.create_timestamp },
                    |m: &mut ProcessFailed| { &mut m.create_timestamp },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ProcessFailed>(
                    "ProcessFailed",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ProcessFailed {
        static mut instance: ::protobuf::lazy::Lazy<ProcessFailed> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ProcessFailed,
        };
        unsafe {
            instance.get(ProcessFailed::new)
        }
    }
}

impl ::protobuf::Clear for ProcessFailed {
    fn clear(&mut self) {
        self.info.clear();
        self.tag = ProcessTag::WORKER;
        self.error.clear();
        self.create_timestamp.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ProcessFailed {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProcessFailed {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ProcessEvent {
    // message oneof groups
    pub payload: ::std::option::Option<ProcessEvent_oneof_payload>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ProcessEvent {
    fn default() -> &'a ProcessEvent {
        <ProcessEvent as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum ProcessEvent_oneof_payload {
    process_started(ProcessStarted),
    process_terminated(ProcessTerminated),
    process_completed(ProcessCompleted),
    process_failed(ProcessFailed),
}

impl ProcessEvent {
    pub fn new() -> ProcessEvent {
        ::std::default::Default::default()
    }

    // .capataz.events.ProcessStarted process_started = 1;


    pub fn get_process_started(&self) -> &ProcessStarted {
        match self.payload {
            ::std::option::Option::Some(ProcessEvent_oneof_payload::process_started(ref v)) => v,
            _ => ProcessStarted::default_instance(),
        }
    }
    pub fn clear_process_started(&mut self) {
        self.payload = ::std::option::Option::None;
    }

    pub fn has_process_started(&self) -> bool {
        match self.payload {
            ::std::option::Option::Some(ProcessEvent_oneof_payload::process_started(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_process_started(&mut self, v: ProcessStarted) {
        self.payload = ::std::option::Option::Some(ProcessEvent_oneof_payload::process_started(v))
    }

    // Mutable pointer to the field.
    pub fn mut_process_started(&mut self) -> &mut ProcessStarted {
        if let ::std::option::Option::Some(ProcessEvent_oneof_payload::process_started(_)) = self.payload {
        } else {
            self.payload = ::std::option::Option::Some(ProcessEvent_oneof_payload::process_started(ProcessStarted::new()));
        }
        match self.payload {
            ::std::option::Option::Some(ProcessEvent_oneof_payload::process_started(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_process_started(&mut self) -> ProcessStarted {
        if self.has_process_started() {
            match self.payload.take() {
                ::std::option::Option::Some(ProcessEvent_oneof_payload::process_started(v)) => v,
                _ => panic!(),
            }
        } else {
            ProcessStarted::new()
        }
    }

    // .capataz.events.ProcessTerminated process_terminated = 2;


    pub fn get_process_terminated(&self) -> &ProcessTerminated {
        match self.payload {
            ::std::option::Option::Some(ProcessEvent_oneof_payload::process_terminated(ref v)) => v,
            _ => ProcessTerminated::default_instance(),
        }
    }
    pub fn clear_process_terminated(&mut self) {
        self.payload = ::std::option::Option::None;
    }

    pub fn has_process_terminated(&self) -> bool {
        match self.payload {
            ::std::option::Option::Some(ProcessEvent_oneof_payload::process_terminated(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_process_terminated(&mut self, v: ProcessTerminated) {
        self.payload = ::std::option::Option::Some(ProcessEvent_oneof_payload::process_terminated(v))
    }

    // Mutable pointer to the field.
    pub fn mut_process_terminated(&mut self) -> &mut ProcessTerminated {
        if let ::std::option::Option::Some(ProcessEvent_oneof_payload::process_terminated(_)) = self.payload {
        } else {
            self.payload = ::std::option::Option::Some(ProcessEvent_oneof_payload::process_terminated(ProcessTerminated::new()));
        }
        match self.payload {
            ::std::option::Option::Some(ProcessEvent_oneof_payload::process_terminated(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_process_terminated(&mut self) -> ProcessTerminated {
        if self.has_process_terminated() {
            match self.payload.take() {
                ::std::option::Option::Some(ProcessEvent_oneof_payload::process_terminated(v)) => v,
                _ => panic!(),
            }
        } else {
            ProcessTerminated::new()
        }
    }

    // .capataz.events.ProcessCompleted process_completed = 3;


    pub fn get_process_completed(&self) -> &ProcessCompleted {
        match self.payload {
            ::std::option::Option::Some(ProcessEvent_oneof_payload::process_completed(ref v)) => v,
            _ => ProcessCompleted::default_instance(),
        }
    }
    pub fn clear_process_completed(&mut self) {
        self.payload = ::std::option::Option::None;
    }

    pub fn has_process_completed(&self) -> bool {
        match self.payload {
            ::std::option::Option::Some(ProcessEvent_oneof_payload::process_completed(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_process_completed(&mut self, v: ProcessCompleted) {
        self.payload = ::std::option::Option::Some(ProcessEvent_oneof_payload::process_completed(v))
    }

    // Mutable pointer to the field.
    pub fn mut_process_completed(&mut self) -> &mut ProcessCompleted {
        if let ::std::option::Option::Some(ProcessEvent_oneof_payload::process_completed(_)) = self.payload {
        } else {
            self.payload = ::std::option::Option::Some(ProcessEvent_oneof_payload::process_completed(ProcessCompleted::new()));
        }
        match self.payload {
            ::std::option::Option::Some(ProcessEvent_oneof_payload::process_completed(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_process_completed(&mut self) -> ProcessCompleted {
        if self.has_process_completed() {
            match self.payload.take() {
                ::std::option::Option::Some(ProcessEvent_oneof_payload::process_completed(v)) => v,
                _ => panic!(),
            }
        } else {
            ProcessCompleted::new()
        }
    }

    // .capataz.events.ProcessFailed process_failed = 4;


    pub fn get_process_failed(&self) -> &ProcessFailed {
        match self.payload {
            ::std::option::Option::Some(ProcessEvent_oneof_payload::process_failed(ref v)) => v,
            _ => ProcessFailed::default_instance(),
        }
    }
    pub fn clear_process_failed(&mut self) {
        self.payload = ::std::option::Option::None;
    }

    pub fn has_process_failed(&self) -> bool {
        match self.payload {
            ::std::option::Option::Some(ProcessEvent_oneof_payload::process_failed(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_process_failed(&mut self, v: ProcessFailed) {
        self.payload = ::std::option::Option::Some(ProcessEvent_oneof_payload::process_failed(v))
    }

    // Mutable pointer to the field.
    pub fn mut_process_failed(&mut self) -> &mut ProcessFailed {
        if let ::std::option::Option::Some(ProcessEvent_oneof_payload::process_failed(_)) = self.payload {
        } else {
            self.payload = ::std::option::Option::Some(ProcessEvent_oneof_payload::process_failed(ProcessFailed::new()));
        }
        match self.payload {
            ::std::option::Option::Some(ProcessEvent_oneof_payload::process_failed(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_process_failed(&mut self) -> ProcessFailed {
        if self.has_process_failed() {
            match self.payload.take() {
                ::std::option::Option::Some(ProcessEvent_oneof_payload::process_failed(v)) => v,
                _ => panic!(),
            }
        } else {
            ProcessFailed::new()
        }
    }
}

impl ::protobuf::Message for ProcessEvent {
    fn is_initialized(&self) -> bool {
        if let Some(ProcessEvent_oneof_payload::process_started(ref v)) = self.payload {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(ProcessEvent_oneof_payload::process_terminated(ref v)) = self.payload {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(ProcessEvent_oneof_payload::process_completed(ref v)) = self.payload {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(ProcessEvent_oneof_payload::process_failed(ref v)) = self.payload {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.payload = ::std::option::Option::Some(ProcessEvent_oneof_payload::process_started(is.read_message()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.payload = ::std::option::Option::Some(ProcessEvent_oneof_payload::process_terminated(is.read_message()?));
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.payload = ::std::option::Option::Some(ProcessEvent_oneof_payload::process_completed(is.read_message()?));
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.payload = ::std::option::Option::Some(ProcessEvent_oneof_payload::process_failed(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.payload {
            match v {
                &ProcessEvent_oneof_payload::process_started(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &ProcessEvent_oneof_payload::process_terminated(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &ProcessEvent_oneof_payload::process_completed(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &ProcessEvent_oneof_payload::process_failed(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.payload {
            match v {
                &ProcessEvent_oneof_payload::process_started(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &ProcessEvent_oneof_payload::process_terminated(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &ProcessEvent_oneof_payload::process_completed(ref v) => {
                    os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &ProcessEvent_oneof_payload::process_failed(ref v) => {
                    os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ProcessEvent {
        ProcessEvent::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ProcessStarted>(
                    "process_started",
                    ProcessEvent::has_process_started,
                    ProcessEvent::get_process_started,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ProcessTerminated>(
                    "process_terminated",
                    ProcessEvent::has_process_terminated,
                    ProcessEvent::get_process_terminated,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ProcessCompleted>(
                    "process_completed",
                    ProcessEvent::has_process_completed,
                    ProcessEvent::get_process_completed,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ProcessFailed>(
                    "process_failed",
                    ProcessEvent::has_process_failed,
                    ProcessEvent::get_process_failed,
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ProcessEvent>(
                    "ProcessEvent",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ProcessEvent {
        static mut instance: ::protobuf::lazy::Lazy<ProcessEvent> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ProcessEvent,
        };
        unsafe {
            instance.get(ProcessEvent::new)
        }
    }
}

impl ::protobuf::Clear for ProcessEvent {
    fn clear(&mut self) {
        self.payload = ::std::option::Option::None;
        self.payload = ::std::option::Option::None;
        self.payload = ::std::option::Option::None;
        self.payload = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ProcessEvent {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProcessEvent {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct EventBundle {
    // message fields
    pub events: ::protobuf::RepeatedField<ProcessEvent>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a EventBundle {
    fn default() -> &'a EventBundle {
        <EventBundle as ::protobuf::Message>::default_instance()
    }
}

impl EventBundle {
    pub fn new() -> EventBundle {
        ::std::default::Default::default()
    }

    // repeated .capataz.events.ProcessEvent events = 1;


    pub fn get_events(&self) -> &[ProcessEvent] {
        &self.events
    }
    pub fn clear_events(&mut self) {
        self.events.clear();
    }

    // Param is passed by value, moved
    pub fn set_events(&mut self, v: ::protobuf::RepeatedField<ProcessEvent>) {
        self.events = v;
    }

    // Mutable pointer to the field.
    pub fn mut_events(&mut self) -> &mut ::protobuf::RepeatedField<ProcessEvent> {
        &mut self.events
    }

    // Take field
    pub fn take_events(&mut self) -> ::protobuf::RepeatedField<ProcessEvent> {
        ::std::mem::replace(&mut self.events, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for EventBundle {
    fn is_initialized(&self) -> bool {
        for v in &self.events {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.events)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.events {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        for v in &self.events {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> EventBundle {
        EventBundle::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ProcessEvent>>(
                    "events",
                    |m: &EventBundle| { &m.events },
                    |m: &mut EventBundle| { &mut m.events },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<EventBundle>(
                    "EventBundle",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static EventBundle {
        static mut instance: ::protobuf::lazy::Lazy<EventBundle> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const EventBundle,
        };
        unsafe {
            instance.get(EventBundle::new)
        }
    }
}

impl ::protobuf::Clear for EventBundle {
    fn clear(&mut self) {
        self.events.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for EventBundle {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for EventBundle {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum ProcessTag {
    WORKER = 0,
    SUPERVISOR = 1,
}

impl ::protobuf::ProtobufEnum for ProcessTag {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ProcessTag> {
        match value {
            0 => ::std::option::Option::Some(ProcessTag::WORKER),
            1 => ::std::option::Option::Some(ProcessTag::SUPERVISOR),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [ProcessTag] = &[
            ProcessTag::WORKER,
            ProcessTag::SUPERVISOR,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("ProcessTag", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for ProcessTag {
}

impl ::std::default::Default for ProcessTag {
    fn default() -> Self {
        ProcessTag::WORKER
    }
}

impl ::protobuf::reflect::ProtobufValue for ProcessTag {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0cevents.proto\x12\x0ecapataz.events\x1a\x1fgoogle/protobuf/timestam\
    p.proto\"d\n\x0bProcessInfo\x12\x19\n\x08event_id\x18\x01\x20\x01(\tR\
    \x07eventId\x12\x1d\n\nprocess_id\x18\x02\x20\x01(\tR\tprocessId\x12\x1b\
    \n\tparent_id\x18\x03\x20\x01(\tR\x08parentId\"\xaf\x02\n\x0eProcessStar\
    ted\x12/\n\x04info\x18\x01\x20\x01(\x0b2\x1b.capataz.events.ProcessInfoR\
    \x04info\x12,\n\x03tag\x18\x02\x20\x01(\x0e2\x1a.capataz.events.ProcessT\
    agR\x03tag\x12E\n\x10create_timestamp\x18\x03\x20\x01(\x0b2\x1a.google.p\
    rotobuf.TimestampR\x0fcreateTimestamp\x12R\n\x17first_restart_timestamp\
    \x18\x04\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\x15firstRestartTim\
    estamp\x12#\n\rrestart_count\x18\x05\x20\x01(\rR\x0crestartCount\"\xb9\
    \x01\n\x11ProcessTerminated\x12/\n\x04info\x18\x01\x20\x01(\x0b2\x1b.cap\
    ataz.events.ProcessInfoR\x04info\x12,\n\x03tag\x18\x02\x20\x01(\x0e2\x1a\
    .capataz.events.ProcessTagR\x03tag\x12E\n\x10create_timestamp\x18\x03\
    \x20\x01(\x0b2\x1a.google.protobuf.TimestampR\x0fcreateTimestamp\"\xb8\
    \x01\n\x10ProcessCompleted\x12/\n\x04info\x18\x01\x20\x01(\x0b2\x1b.capa\
    taz.events.ProcessInfoR\x04info\x12,\n\x03tag\x18\x02\x20\x01(\x0e2\x1a.\
    capataz.events.ProcessTagR\x03tag\x12E\n\x10create_timestamp\x18\x03\x20\
    \x01(\x0b2\x1a.google.protobuf.TimestampR\x0fcreateTimestamp\"\xcb\x01\n\
    \rProcessFailed\x12/\n\x04info\x18\x01\x20\x01(\x0b2\x1b.capataz.events.\
    ProcessInfoR\x04info\x12,\n\x03tag\x18\x02\x20\x01(\x0e2\x1a.capataz.eve\
    nts.ProcessTagR\x03tag\x12\x14\n\x05error\x18\x03\x20\x01(\tR\x05error\
    \x12E\n\x10create_timestamp\x18\x04\x20\x01(\x0b2\x1a.google.protobuf.Ti\
    mestampR\x0fcreateTimestamp\"\xd1\x02\n\x0cProcessEvent\x12I\n\x0fproces\
    s_started\x18\x01\x20\x01(\x0b2\x1e.capataz.events.ProcessStartedH\0R\
    \x0eprocessStarted\x12R\n\x12process_terminated\x18\x02\x20\x01(\x0b2!.c\
    apataz.events.ProcessTerminatedH\0R\x11processTerminated\x12O\n\x11proce\
    ss_completed\x18\x03\x20\x01(\x0b2\x20.capataz.events.ProcessCompletedH\
    \0R\x10processCompleted\x12F\n\x0eprocess_failed\x18\x04\x20\x01(\x0b2\
    \x1d.capataz.events.ProcessFailedH\0R\rprocessFailedB\t\n\x07payload\"C\
    \n\x0bEventBundle\x124\n\x06events\x18\x01\x20\x03(\x0b2\x1c.capataz.eve\
    nts.ProcessEventR\x06events*(\n\nProcessTag\x12\n\n\x06WORKER\x10\0\x12\
    \x0e\n\nSUPERVISOR\x10\x01J\xe2\x0e\n\x06\x12\x04\0\07\x01\n\x08\n\x01\
    \x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0\x17\n\t\n\x02\x03\0\
    \x12\x03\x04\0)\n\n\n\x02\x05\0\x12\x04\x06\0\t\x01\n\n\n\x03\x05\0\x01\
    \x12\x03\x06\x05\x0f\n\x0b\n\x04\x05\0\x02\0\x12\x03\x07\x02\r\n\x0c\n\
    \x05\x05\0\x02\0\x01\x12\x03\x07\x02\x08\n\x0c\n\x05\x05\0\x02\0\x02\x12\
    \x03\x07\x0b\x0c\n\x0b\n\x04\x05\0\x02\x01\x12\x03\x08\x02\x11\n\x0c\n\
    \x05\x05\0\x02\x01\x01\x12\x03\x08\x02\x0c\n\x0c\n\x05\x05\0\x02\x01\x02\
    \x12\x03\x08\x0f\x10\n\n\n\x02\x04\0\x12\x04\x0b\0\x0f\x01\n\n\n\x03\x04\
    \0\x01\x12\x03\x0b\x08\x13\n\x0b\n\x04\x04\0\x02\0\x12\x03\x0c\x02\x17\n\
    \r\n\x05\x04\0\x02\0\x04\x12\x04\x0c\x02\x0b\x15\n\x0c\n\x05\x04\0\x02\0\
    \x05\x12\x03\x0c\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x0c\t\x11\n\
    \x0c\n\x05\x04\0\x02\0\x03\x12\x03\x0c\x15\x16\n\x0b\n\x04\x04\0\x02\x01\
    \x12\x03\r\x02\x18\n\r\n\x05\x04\0\x02\x01\x04\x12\x04\r\x02\x0c\x17\n\
    \x0c\n\x05\x04\0\x02\x01\x05\x12\x03\r\x02\x08\n\x0c\n\x05\x04\0\x02\x01\
    \x01\x12\x03\r\t\x13\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\r\x16\x17\n\
    \x0b\n\x04\x04\0\x02\x02\x12\x03\x0e\x02\x17\n\r\n\x05\x04\0\x02\x02\x04\
    \x12\x04\x0e\x02\r\x18\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x0e\x02\x08\
    \n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x0e\t\x12\n\x0c\n\x05\x04\0\x02\
    \x02\x03\x12\x03\x0e\x15\x16\n\n\n\x02\x04\x01\x12\x04\x11\0\x17\x01\n\n\
    \n\x03\x04\x01\x01\x12\x03\x11\x08\x16\n\x0b\n\x04\x04\x01\x02\0\x12\x03\
    \x12\x02\x17\n\r\n\x05\x04\x01\x02\0\x04\x12\x04\x12\x02\x11\x18\n\x0c\n\
    \x05\x04\x01\x02\0\x06\x12\x03\x12\x02\r\n\x0c\n\x05\x04\x01\x02\0\x01\
    \x12\x03\x12\x0e\x12\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x12\x15\x16\n\
    \x0b\n\x04\x04\x01\x02\x01\x12\x03\x13\x02\x15\n\r\n\x05\x04\x01\x02\x01\
    \x04\x12\x04\x13\x02\x12\x17\n\x0c\n\x05\x04\x01\x02\x01\x06\x12\x03\x13\
    \x02\x0c\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\x13\r\x10\n\x0c\n\x05\
    \x04\x01\x02\x01\x03\x12\x03\x13\x13\x14\n\x0b\n\x04\x04\x01\x02\x02\x12\
    \x03\x14\x021\n\r\n\x05\x04\x01\x02\x02\x04\x12\x04\x14\x02\x13\x15\n\
    \x0c\n\x05\x04\x01\x02\x02\x06\x12\x03\x14\x02\x1b\n\x0c\n\x05\x04\x01\
    \x02\x02\x01\x12\x03\x14\x1c,\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\
    \x14/0\n\x0b\n\x04\x04\x01\x02\x03\x12\x03\x15\x028\n\r\n\x05\x04\x01\
    \x02\x03\x04\x12\x04\x15\x02\x141\n\x0c\n\x05\x04\x01\x02\x03\x06\x12\
    \x03\x15\x02\x1b\n\x0c\n\x05\x04\x01\x02\x03\x01\x12\x03\x15\x1c3\n\x0c\
    \n\x05\x04\x01\x02\x03\x03\x12\x03\x1567\n\x0b\n\x04\x04\x01\x02\x04\x12\
    \x03\x16\x02\x1b\n\r\n\x05\x04\x01\x02\x04\x04\x12\x04\x16\x02\x158\n\
    \x0c\n\x05\x04\x01\x02\x04\x05\x12\x03\x16\x02\x08\n\x0c\n\x05\x04\x01\
    \x02\x04\x01\x12\x03\x16\t\x16\n\x0c\n\x05\x04\x01\x02\x04\x03\x12\x03\
    \x16\x19\x1a\n\n\n\x02\x04\x02\x12\x04\x19\0\x1d\x01\n\n\n\x03\x04\x02\
    \x01\x12\x03\x19\x08\x19\n\x0b\n\x04\x04\x02\x02\0\x12\x03\x1a\x02\x17\n\
    \r\n\x05\x04\x02\x02\0\x04\x12\x04\x1a\x02\x19\x1b\n\x0c\n\x05\x04\x02\
    \x02\0\x06\x12\x03\x1a\x02\r\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03\x1a\
    \x0e\x12\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03\x1a\x15\x16\n\x0b\n\x04\
    \x04\x02\x02\x01\x12\x03\x1b\x02\x15\n\r\n\x05\x04\x02\x02\x01\x04\x12\
    \x04\x1b\x02\x1a\x17\n\x0c\n\x05\x04\x02\x02\x01\x06\x12\x03\x1b\x02\x0c\
    \n\x0c\n\x05\x04\x02\x02\x01\x01\x12\x03\x1b\r\x10\n\x0c\n\x05\x04\x02\
    \x02\x01\x03\x12\x03\x1b\x13\x14\n\x0b\n\x04\x04\x02\x02\x02\x12\x03\x1c\
    \x021\n\r\n\x05\x04\x02\x02\x02\x04\x12\x04\x1c\x02\x1b\x15\n\x0c\n\x05\
    \x04\x02\x02\x02\x06\x12\x03\x1c\x02\x1b\n\x0c\n\x05\x04\x02\x02\x02\x01\
    \x12\x03\x1c\x1c,\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x03\x1c/0\n\n\n\
    \x02\x04\x03\x12\x04\x1f\0#\x01\n\n\n\x03\x04\x03\x01\x12\x03\x1f\x08\
    \x18\n\x0b\n\x04\x04\x03\x02\0\x12\x03\x20\x02\x17\n\r\n\x05\x04\x03\x02\
    \0\x04\x12\x04\x20\x02\x1f\x1a\n\x0c\n\x05\x04\x03\x02\0\x06\x12\x03\x20\
    \x02\r\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03\x20\x0e\x12\n\x0c\n\x05\x04\
    \x03\x02\0\x03\x12\x03\x20\x15\x16\n\x0b\n\x04\x04\x03\x02\x01\x12\x03!\
    \x02\x15\n\r\n\x05\x04\x03\x02\x01\x04\x12\x04!\x02\x20\x17\n\x0c\n\x05\
    \x04\x03\x02\x01\x06\x12\x03!\x02\x0c\n\x0c\n\x05\x04\x03\x02\x01\x01\
    \x12\x03!\r\x10\n\x0c\n\x05\x04\x03\x02\x01\x03\x12\x03!\x13\x14\n\x0b\n\
    \x04\x04\x03\x02\x02\x12\x03\"\x021\n\r\n\x05\x04\x03\x02\x02\x04\x12\
    \x04\"\x02!\x15\n\x0c\n\x05\x04\x03\x02\x02\x06\x12\x03\"\x02\x1b\n\x0c\
    \n\x05\x04\x03\x02\x02\x01\x12\x03\"\x1c,\n\x0c\n\x05\x04\x03\x02\x02\
    \x03\x12\x03\"/0\n\n\n\x02\x04\x04\x12\x04%\0*\x01\n\n\n\x03\x04\x04\x01\
    \x12\x03%\x08\x15\n\x0b\n\x04\x04\x04\x02\0\x12\x03&\x02\x17\n\r\n\x05\
    \x04\x04\x02\0\x04\x12\x04&\x02%\x17\n\x0c\n\x05\x04\x04\x02\0\x06\x12\
    \x03&\x02\r\n\x0c\n\x05\x04\x04\x02\0\x01\x12\x03&\x0e\x12\n\x0c\n\x05\
    \x04\x04\x02\0\x03\x12\x03&\x15\x16\n\x0b\n\x04\x04\x04\x02\x01\x12\x03'\
    \x02\x15\n\r\n\x05\x04\x04\x02\x01\x04\x12\x04'\x02&\x17\n\x0c\n\x05\x04\
    \x04\x02\x01\x06\x12\x03'\x02\x0c\n\x0c\n\x05\x04\x04\x02\x01\x01\x12\
    \x03'\r\x10\n\x0c\n\x05\x04\x04\x02\x01\x03\x12\x03'\x13\x14\n\x0b\n\x04\
    \x04\x04\x02\x02\x12\x03(\x02\x13\n\r\n\x05\x04\x04\x02\x02\x04\x12\x04(\
    \x02'\x15\n\x0c\n\x05\x04\x04\x02\x02\x05\x12\x03(\x02\x08\n\x0c\n\x05\
    \x04\x04\x02\x02\x01\x12\x03(\t\x0e\n\x0c\n\x05\x04\x04\x02\x02\x03\x12\
    \x03(\x11\x12\n\x0b\n\x04\x04\x04\x02\x03\x12\x03)\x021\n\r\n\x05\x04\
    \x04\x02\x03\x04\x12\x04)\x02(\x13\n\x0c\n\x05\x04\x04\x02\x03\x06\x12\
    \x03)\x02\x1b\n\x0c\n\x05\x04\x04\x02\x03\x01\x12\x03)\x1c,\n\x0c\n\x05\
    \x04\x04\x02\x03\x03\x12\x03)/0\n\n\n\x02\x04\x05\x12\x04,\03\x01\n\n\n\
    \x03\x04\x05\x01\x12\x03,\x08\x14\n\x0c\n\x04\x04\x05\x08\0\x12\x04-\x02\
    2\x03\n\x0c\n\x05\x04\x05\x08\0\x01\x12\x03-\x08\x0f\n\x0b\n\x04\x04\x05\
    \x02\0\x12\x03.\x04'\n\x0c\n\x05\x04\x05\x02\0\x06\x12\x03.\x04\x12\n\
    \x0c\n\x05\x04\x05\x02\0\x01\x12\x03.\x13\"\n\x0c\n\x05\x04\x05\x02\0\
    \x03\x12\x03.%&\n\x0b\n\x04\x04\x05\x02\x01\x12\x03/\x04-\n\x0c\n\x05\
    \x04\x05\x02\x01\x06\x12\x03/\x04\x15\n\x0c\n\x05\x04\x05\x02\x01\x01\
    \x12\x03/\x16(\n\x0c\n\x05\x04\x05\x02\x01\x03\x12\x03/+,\n\x0b\n\x04\
    \x04\x05\x02\x02\x12\x030\x04+\n\x0c\n\x05\x04\x05\x02\x02\x06\x12\x030\
    \x04\x14\n\x0c\n\x05\x04\x05\x02\x02\x01\x12\x030\x15&\n\x0c\n\x05\x04\
    \x05\x02\x02\x03\x12\x030)*\n\x0b\n\x04\x04\x05\x02\x03\x12\x031\x04%\n\
    \x0c\n\x05\x04\x05\x02\x03\x06\x12\x031\x04\x11\n\x0c\n\x05\x04\x05\x02\
    \x03\x01\x12\x031\x12\x20\n\x0c\n\x05\x04\x05\x02\x03\x03\x12\x031#$\n\n\
    \n\x02\x04\x06\x12\x045\07\x01\n\n\n\x03\x04\x06\x01\x12\x035\x08\x13\n\
    \x0b\n\x04\x04\x06\x02\0\x12\x036\x02#\n\x0c\n\x05\x04\x06\x02\0\x04\x12\
    \x036\x02\n\n\x0c\n\x05\x04\x06\x02\0\x06\x12\x036\x0b\x17\n\x0c\n\x05\
    \x04\x06\x02\0\x01\x12\x036\x18\x1e\n\x0c\n\x05\x04\x06\x02\0\x03\x12\
    \x036!\"b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
